CLASS zbp_r_cs03_statistic DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zr_cs03_statistic.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_r_cs03_statistic IMPLEMENTATION.
ENDCLASS.
