CLASS zcl_plz_setup_03 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.

ENDCLASS.


CLASS zcl_plz_setup_03 IMPLEMENTATION.

  METHOD if_oo_adt_classrun~main.

    DATA lt_plz TYPE STANDARD TABLE OF zcs03_plz_city.

    lt_plz = VALUE #(
      ( client = sy-mandt postcode = '97340' city = 'Segnitz' )
      ( client = sy-mandt postcode = '97342' city = 'Seinsheim' )
      ( client = sy-mandt postcode = '97346' city = 'Iphofen' )
      ( client = sy-mandt postcode = '97348' city = 'Rödelsee' )
      ( client = sy-mandt postcode = '97350' city = 'Mainbernheim' )
      ( client = sy-mandt postcode = '97353' city = 'Wiesentheid' )
      ( client = sy-mandt postcode = '97355' city = 'Castell' )
      ( client = sy-mandt postcode = '97357' city = 'Prichsenstadt' )
      ( client = sy-mandt postcode = '97359' city = 'Schwarzach am Main' )
      ( client = sy-mandt postcode = '97412' city = 'Schweinfurt' )
      ( client = sy-mandt postcode = '97418' city = 'Agentur für Arbeit Schweinfurt' )
      ( client = sy-mandt postcode = '97419' city = 'Leopoldina Krankenhaus' )
      ( client = sy-mandt postcode = '97420' city = 'Stadtverwaltung' )
      ( client = sy-mandt postcode = '97421' city = 'Schweinfurt' )
      ( client = sy-mandt postcode = '97422' city = 'Schweinfurt' )
      ( client = sy-mandt postcode = '97424' city = 'Schweinfurt' )
      ( client = sy-mandt postcode = '97437' city = 'Haßfurt' )
      ( client = sy-mandt postcode = '97440' city = 'Werneck' )
      ( client = sy-mandt postcode = '97447' city = 'Gerolzhofen' )
      ( client = sy-mandt postcode = '97450' city = 'Arnstein' )
      ( client = sy-mandt postcode = '97453' city = 'Schonungen' )
      ( client = sy-mandt postcode = '97456' city = 'Dittelbrunn' )
      ( client = sy-mandt postcode = '97461' city = 'Hofheim in Unterfranken' )
      ( client = sy-mandt postcode = '97464' city = 'Niederwerrn' )
      ( client = sy-mandt postcode = '97469' city = 'Gochsheim' )
      ( client = sy-mandt postcode = '97475' city = 'Zeil am Main' )
      ( client = sy-mandt postcode = '97478' city = 'Knetzgau' )
      ( client = sy-mandt postcode = '97483' city = 'Eltmann' )
      ( client = sy-mandt postcode = '97486' city = 'Königsberg in Bayern' )
      ( client = sy-mandt postcode = '97488' city = 'Stadtlauringen' )
      ( client = sy-mandt postcode = '97490' city = 'Poppenhausen' )
      ( client = sy-mandt postcode = '97491' city = 'Aidhausen' )
      ( client = sy-mandt postcode = '97493' city = 'Bergrheinfeld' )
      ( client = sy-mandt postcode = '97494' city = 'Bundorf' )
      ( client = sy-mandt postcode = '97496' city = 'Burgpreppach' )
      ( client = sy-mandt postcode = '97497' city = 'Dingolshausen' )
      ( client = sy-mandt postcode = '97499' city = 'Donnersdorf' )
      ( client = sy-mandt postcode = '97500' city = 'Ebelsbach' )
      ( client = sy-mandt postcode = '97502' city = 'Euerbach' )
      ( client = sy-mandt postcode = '97503' city = 'Gädheim' )
      ( client = sy-mandt postcode = '97505' city = 'Geldersheim' )
      ( client = sy-mandt postcode = '97506' city = 'Grafenrheinfeld' )
      ( client = sy-mandt postcode = '97508' city = 'Grettstadt' )
      ( client = sy-mandt postcode = '97509' city = 'Kolitzheim' )
      ( client = sy-mandt postcode = '97511' city = 'Lülsfeld' )
      ( client = sy-mandt postcode = '97513' city = 'Michelau im Steigerwald' )
      ( client = sy-mandt postcode = '97514' city = 'Oberaurach' )
      ( client = sy-mandt postcode = '97516' city = 'Oberschwarzach' )
      ( client = sy-mandt postcode = '97517' city = 'Rannungen' )
      ( client = sy-mandt postcode = '97519' city = 'Riedbach' )
      ( client = sy-mandt postcode = '97520' city = 'Röthlein' )
      ( client = sy-mandt postcode = '97522' city = 'Sand am Main' )
      ( client = sy-mandt postcode = '97523' city = 'Schwanfeld' )
      ( client = sy-mandt postcode = '97525' city = 'Schwebheim' )
      ( client = sy-mandt postcode = '97526' city = 'Sennfeld' )
      ( client = sy-mandt postcode = '97528' city = 'Sulzdorf an der Lederhecke' )
      ( client = sy-mandt postcode = '97529' city = 'Sulzheim' )
      ( client = sy-mandt postcode = '97531' city = 'Theres' )
      ( client = sy-mandt postcode = '97532' city = 'Üchtelhausen' )
      ( client = sy-mandt postcode = '97534' city = 'Waigolshausen' )
      ( client = sy-mandt postcode = '97535' city = 'Wasserlosen' )
      ( client = sy-mandt postcode = '97537' city = 'Wipfeld' )
      ( client = sy-mandt postcode = '97539' city = 'Wonfurt' )
      ( client = sy-mandt postcode = '97615' city = 'Amtsgericht' )
      ( client = sy-mandt postcode = '97616' city = 'Salz' )
      ( client = sy-mandt postcode = '97618' city = 'Unsleben' )
      ( client = sy-mandt postcode = '97631' city = 'Bad Königshofen im Grabfeld' )
      ( client = sy-mandt postcode = '97633' city = 'Höchheim' )
      ( client = sy-mandt postcode = '97638' city = 'Mellrichstadt' )
      ( client = sy-mandt postcode = '97640' city = 'Hendungen' )
      ( client = sy-mandt postcode = '97645' city = 'Ostheim vor der Rhön' )
      ( client = sy-mandt postcode = '97647' city = 'Hausen' )
      ( client = sy-mandt postcode = '97650' city = 'Fladungen' )
      ( client = sy-mandt postcode = '97653' city = 'Bischofsheim an der Rhön' )
      ( client = sy-mandt postcode = '97654' city = 'Bastheim' )
      ( client = sy-mandt postcode = '97656' city = 'Oberelsbach' )
      ( client = sy-mandt postcode = '97657' city = 'Sandberg' )
      ( client = sy-mandt postcode = '97659' city = 'Schönau an der Brend' )
      ( client = sy-mandt postcode = '97685' city = 'Landratsamt' )
      ( client = sy-mandt postcode = '97688' city = 'Bad Kissingen' )
      ( client = sy-mandt postcode = '97702' city = 'Münnerstadt' )
      ( client = sy-mandt postcode = '97705' city = 'Burkardroth' )
      ( client = sy-mandt postcode = '97708' city = 'Bad Bocklet' )
      ( client = sy-mandt postcode = '97711' city = 'Maßbach' )
      ( client = sy-mandt postcode = '97714' city = 'Oerlenbach' )
      ( client = sy-mandt postcode = '97717' city = 'Euerdorf' )
      ( client = sy-mandt postcode = '97720' city = 'Nüdlingen' )
      ( client = sy-mandt postcode = '97723' city = 'Oberthulba' )
      ( client = sy-mandt postcode = '97724' city = 'Burglauer' )
      ( client = sy-mandt postcode = '97725' city = 'Elfershausen' )
      ( client = sy-mandt postcode = '97727' city = 'Fuchsstadt' )
      ( client = sy-mandt postcode = '97729' city = 'Ramsthal' )
      ( client = sy-mandt postcode = '97737' city = 'Gemünden am Main' )
      ( client = sy-mandt postcode = '97753' city = 'Karlstadt' )
      ( client = sy-mandt postcode = '97762' city = 'Hammelburg' )
      ( client = sy-mandt postcode = '97769' city = 'Bad Brückenau' )
      ( client = sy-mandt postcode = '97772' city = 'Wildflecken' )
      ( client = sy-mandt postcode = '97773' city = 'Aura im Sinngrund' )
      ( client = sy-mandt postcode = '97775' city = 'Burgsinn' )
      ( client = sy-mandt postcode = '97776' city = 'Eußenheim' )
      ( client = sy-mandt postcode = '97778' city = 'Fellen' )
      ( client = sy-mandt postcode = '97779' city = 'Geroda' )
      ( client = sy-mandt postcode = '97780' city = 'Gössenheim' )
      ( client = sy-mandt postcode = '97782' city = 'Gräfendorf' )
      ( client = sy-mandt postcode = '97783' city = 'Karsbach' )
      ( client = sy-mandt postcode = '97785' city = 'Mittelsinn' )
      ( client = sy-mandt postcode = '97786' city = 'Motten' )
      ( client = sy-mandt postcode = '97788' city = 'Neuendorf' )
      ( client = sy-mandt postcode = '97789' city = 'Oberleichtersbach' )
      ( client = sy-mandt postcode = '97791' city = 'Obersinn' )
      ( client = sy-mandt postcode = '97792' city = 'Riedenberg' )
      ( client = sy-mandt postcode = '97794' city = 'Rieneck' )
      ( client = sy-mandt postcode = '97795' city = 'Schondra' )
      ( client = sy-mandt postcode = '97797' city = 'Wartmannsroth' )
      ( client = sy-mandt postcode = '97799' city = 'Zeitlofs' )
      ( client = sy-mandt postcode = '97813' city = 'Bosch Rexroth AG' )
      ( client = sy-mandt postcode = '97814' city = 'Bosch Rexroth AG' )
      ( client = sy-mandt postcode = '97816' city = 'Lohr am Main' )
      ( client = sy-mandt postcode = '97828' city = 'Marktheidenfeld' )
      ( client = sy-mandt postcode = '97833' city = 'Frammersbach' )
      ( client = sy-mandt postcode = '97834' city = 'Birkenfeld' )
      ( client = sy-mandt postcode = '97836' city = 'Bischbrunn' )
      ( client = sy-mandt postcode = '97837' city = 'Erlenbach bei Marktheidenfeld' )
      ( client = sy-mandt postcode = '97839' city = 'Esselbach' )
      ( client = sy-mandt postcode = '97840' city = 'Hafenlohr' )
      ( client = sy-mandt postcode = '97842' city = 'Karbach' )
      ( client = sy-mandt postcode = '97843' city = 'Neuhütten' )
      ( client = sy-mandt postcode = '97845' city = 'Neustadt am Main' )
      ( client = sy-mandt postcode = '97846' city = 'Partenstein' )
      ( client = sy-mandt postcode = '97848' city = 'Rechtenbach' )
      ( client = sy-mandt postcode = '97849' city = 'Roden' )
      ( client = sy-mandt postcode = '97851' city = 'Rothenfels' )
      ( client = sy-mandt postcode = '97852' city = 'Schollbrunn' )
      ( client = sy-mandt postcode = '97854' city = 'Steinfeld' )
      ( client = sy-mandt postcode = '97855' city = 'Triefenstein' )
      ( client = sy-mandt postcode = '97857' city = 'Urspringen' )
      ( client = sy-mandt postcode = '97859' city = 'Wiesthal' )
      ( client = sy-mandt postcode = '97877' city = 'Wertheim' )
      ( client = sy-mandt postcode = '97892' city = 'Kreuzwertheim' )
      ( client = sy-mandt postcode = '97896' city = 'Freudenberg' )
      ( client = sy-mandt postcode = '97900' city = 'Külsheim' )
      ( client = sy-mandt postcode = '97901' city = 'Altenbuch' )
      ( client = sy-mandt postcode = '97903' city = 'Collenberg' )
      ( client = sy-mandt postcode = '97904' city = 'Dorfprozelten' )
      ( client = sy-mandt postcode = '97906' city = 'Faulbach' )
      ( client = sy-mandt postcode = '97907' city = 'Hasloch' )
      ( client = sy-mandt postcode = '97909' city = 'Stadtprozelten' )
      ( client = sy-mandt postcode = '97922' city = 'Lauda-Königshofen' )
      ( client = sy-mandt postcode = '97941' city = 'Tauberbischofsheim' )
      ( client = sy-mandt postcode = '97944' city = 'Boxberg' )
      ( client = sy-mandt postcode = '97947' city = 'Grünsfeld' )
      ( client = sy-mandt postcode = '97950' city = 'Großrinderfeld' )
      ( client = sy-mandt postcode = '97953' city = 'Königheim' )
      ( client = sy-mandt postcode = '97956' city = 'Werbach' )
      ( client = sy-mandt postcode = '97957' city = 'Wittighausen' )
      ( client = sy-mandt postcode = '97959' city = 'Assamstadt' )
      ( client = sy-mandt postcode = '97980' city = 'Bad Mergentheim' )
      ( client = sy-mandt postcode = '97990' city = 'Weikersheim' )
      ( client = sy-mandt postcode = '97993' city = 'Creglingen' )
      ( client = sy-mandt postcode = '97996' city = 'Niederstetten' )
      ( client = sy-mandt postcode = '97999' city = 'Igersheim' )
      ( client = sy-mandt postcode = '98496' city = 'Agentur für Arbeit Thüringen S' )
      ( client = sy-mandt postcode = '98497' city = 'Agentur für Arbeit Thüringen S' )
      ( client = sy-mandt postcode = '98523' city = 'AOK PLUS - Die Gesundheitskass' )
      ( client = sy-mandt postcode = '98527' city = 'Suhl' )
      ( client = sy-mandt postcode = '98528' city = 'Suhl' )
      ( client = sy-mandt postcode = '98529' city = 'Suhl' )
      ( client = sy-mandt postcode = '98530' city = 'Rohr' )
      ( client = sy-mandt postcode = '98544' city = 'Zella-Mehlis' )
      ( client = sy-mandt postcode = '98547' city = 'Viernau' )
      ( client = sy-mandt postcode = '98553' city = 'Ahlstädt' )
      ( client = sy-mandt postcode = '98554' city = 'Benshausen' )
      ( client = sy-mandt postcode = '98559' city = 'Oberhof' )
      ( client = sy-mandt postcode = '98574' city = 'Schmalkalden' )
      ( client = sy-mandt postcode = '98587' city = 'Bermbach' )
      ( client = sy-mandt postcode = '98590' city = 'Rosa' )
      ( client = sy-mandt postcode = '98593' city = 'Floh-Seligenthal' )
      ( client = sy-mandt postcode = '98596' city = 'Trusetal' )
      ( client = sy-mandt postcode = '98597' city = 'Heßles' )
      ( client = sy-mandt postcode = '98599' city = 'Brotterode' )
      ( client = sy-mandt postcode = '98610' city = 'Rhön-Rennsteig-Sparkasse Meini' )
      ( client = sy-mandt postcode = '98617' city = 'Herpf' )
      ( client = sy-mandt postcode = '98630' city = 'Milz' )
      ( client = sy-mandt postcode = '98631' city = 'Bibra' )
      ( client = sy-mandt postcode = '98634' city = 'Birx' )
      ( client = sy-mandt postcode = '98639' city = 'Metzels' )
      ( client = sy-mandt postcode = '98646' city = 'Siegritz' )
      ( client = sy-mandt postcode = '98660' city = 'Themar' )
      ( client = sy-mandt postcode = '98663' city = 'Hellingen' )
      ( client = sy-mandt postcode = '98666' city = 'Masserberg' )
      ( client = sy-mandt postcode = '98667' city = 'Schleusegrund' )
      ( client = sy-mandt postcode = '98669' city = 'Veilsdorf' )
      ( client = sy-mandt postcode = '98673' city = 'Brünn' )
      ( client = sy-mandt postcode = '98678' city = 'Sachsenbrunn' )
      ( client = sy-mandt postcode = '98693' city = 'Ilmenau' )
      ( client = sy-mandt postcode = '98701' city = 'Böhlen' )
      ( client = sy-mandt postcode = '98704' city = 'Wolfsberg' )
      ( client = sy-mandt postcode = '98708' city = 'Gehren' )
      ( client = sy-mandt postcode = '98711' city = 'Frauenwald' )
      ( client = sy-mandt postcode = '98714' city = 'Stützerbach' )
      ( client = sy-mandt postcode = '98716' city = 'Geraberg' )
      ( client = sy-mandt postcode = '98724' city = 'Lauscha' )
      ( client = sy-mandt postcode = '98739' city = 'Piesau' )
      ( client = sy-mandt postcode = '98743' city = 'Gräfenthal' )
      ( client = sy-mandt postcode = '98744' city = 'Meura' )
      ( client = sy-mandt postcode = '98746' city = 'Katzhütte' )
      ( client = sy-mandt postcode = '98749' city = 'Steinheid' )
      ( client = sy-mandt postcode = '99060' city = 'Zalando Logistics SE & Co. KG' )
      ( client = sy-mandt postcode = '99068' city = 'Agentur für Arbeit Thüringen M' )
      ( client = sy-mandt postcode = '99073' city = 'OBI Bau- und Heimwerkermärkte ' )
      ( client = sy-mandt postcode = '99075' city = 'Deutsche Post, Geschäftsbereic' )
      ( client = sy-mandt postcode = '99077' city = 'Commerzbank AG Erfurt' )
      ( client = sy-mandt postcode = '99078' city = 'Cellway Kommunikationsdienste' )
      ( client = sy-mandt postcode = '99079' city = 'N.L. Chrestensen Erfurter Same' )
      ( client = sy-mandt postcode = '99080' city = 'Mitteldeutscher Rundfunk Lande' )
      ( client = sy-mandt postcode = '99081' city = 'Kinderkanal ARD/ ZDF' )
      ( client = sy-mandt postcode = '99084' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99085' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99086' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99087' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99089' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99091' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99092' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99094' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99096' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99097' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99098' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99099' city = 'Erfurt' )
      ( client = sy-mandt postcode = '99100' city = 'Dachwig' )
      ( client = sy-mandt postcode = '99102' city = 'Klettbach' )
      ( client = sy-mandt postcode = '99111' city = 'Stadtverwaltung Erfurt Abteilu' )
      ( client = sy-mandt postcode = '99112' city = 'HUK-Coburg' )
      ( client = sy-mandt postcode = '99113' city = 'Bundesarbeitsgericht' )
      ( client = sy-mandt postcode = '99114' city = 'Deutsche Post AG Niederlassung' )
      ( client = sy-mandt postcode = '99115' city = 'OBI-Systemzentrale Außenstelle' )
      ( client = sy-mandt postcode = '99116' city = 'Vodafone Customer Care GmbH' )
      ( client = sy-mandt postcode = '99117' city = 'Deutsche Rentenversicherung Er' )
      ( client = sy-mandt postcode = '99130' city = 'Marlishausen' )
      ( client = sy-mandt postcode = '99189' city = 'Gebesee' )
      ( client = sy-mandt postcode = '99192' city = 'Gamstädt' )
      ( client = sy-mandt postcode = '99195' city = 'Nöda' )
      ( client = sy-mandt postcode = '99198' city = 'Udestedt' )
      ( client = sy-mandt postcode = '99310' city = 'Arnstadt' )
      ( client = sy-mandt postcode = '99326' city = 'Ilmtal' )
      ( client = sy-mandt postcode = '99330' city = 'Crawinkel' )
      ( client = sy-mandt postcode = '99334' city = 'Elleben' )
      ( client = sy-mandt postcode = '99338' city = 'Plaue' )
      ( client = sy-mandt postcode = '99420' city = 'Staatliche Lotterie-Einnahme H' )
      ( client = sy-mandt postcode = '99421' city = 'Amtsgericht Weimar' )
      ( client = sy-mandt postcode = '99423' city = 'Weimar' )
      ( client = sy-mandt postcode = '99425' city = 'Weimar' )
      ( client = sy-mandt postcode = '99427' city = 'Weimar' )
      ( client = sy-mandt postcode = '99428' city = 'Nohra' )
      ( client = sy-mandt postcode = '99437' city = 'Zentralklinik Bad Berka GmbH' )
      ( client = sy-mandt postcode = '99438' city = 'Oettern' )
      ( client = sy-mandt postcode = '99439' city = 'Ramsla' )
      ( client = sy-mandt postcode = '99441' city = 'Magdala' )
      ( client = sy-mandt postcode = '99444' city = 'Blankenhain' )
      ( client = sy-mandt postcode = '99448' city = 'Nauendorf' )
      ( client = sy-mandt postcode = '99510' city = 'Apolda' )
      ( client = sy-mandt postcode = '99518' city = 'Reisdorf' )
      ( client = sy-mandt postcode = '99610' city = 'Sprötau' )
      ( client = sy-mandt postcode = '99625' city = 'Kölleda' )
      ( client = sy-mandt postcode = '99628' city = 'Buttstädt' )
      ( client = sy-mandt postcode = '99631' city = 'Günstedt' )
      ( client = sy-mandt postcode = '99634' city = 'Straußfurt' )
      ( client = sy-mandt postcode = '99636' city = 'Rastenberg' )
      ( client = sy-mandt postcode = '99638' city = 'Büchel' )
      ( client = sy-mandt postcode = '99706' city = 'Sondershausen' )
      ( client = sy-mandt postcode = '99707' city = 'Badra' )
      ( client = sy-mandt postcode = '99713' city = 'Ebeleben' )
      ( client = sy-mandt postcode = '99718' city = 'Trebra' )
      ( client = sy-mandt postcode = '99734' city = 'Nordhausen' )
      ( client = sy-mandt postcode = '99735' city = 'Nohra' )
      ( client = sy-mandt postcode = '99738' city = 'Agentur für Arbeit Thüringen N' )
      ( client = sy-mandt postcode = '99752' city = 'Kraja' )
      ( client = sy-mandt postcode = '99755' city = 'Ellrich' )
      ( client = sy-mandt postcode = '99759' city = 'Rehungen' )
      ( client = sy-mandt postcode = '99762' city = 'Buchholz' )
      ( client = sy-mandt postcode = '99765' city = 'Hamma' )
      ( client = sy-mandt postcode = '99768' city = 'Ilfeld' )
      ( client = sy-mandt postcode = '99815' city = 'Deutsche Post AG Filialbezirks' )
      ( client = sy-mandt postcode = '99817' city = 'Eisenach' )
      ( client = sy-mandt postcode = '99819' city = 'Marksuhl' )
      ( client = sy-mandt postcode = '99820' city = 'Behringen' )
      ( client = sy-mandt postcode = '99826' city = 'Nazza' )
      ( client = sy-mandt postcode = '99830' city = 'Treffurt' )
      ( client = sy-mandt postcode = '99831' city = 'Ifta' )
      ( client = sy-mandt postcode = '99834' city = 'Oberellen' )
      ( client = sy-mandt postcode = '99837' city = 'Dippach' )
      ( client = sy-mandt postcode = '99842' city = 'Ruhla' )
      ( client = sy-mandt postcode = '99846' city = 'Seebach' )
      ( client = sy-mandt postcode = '99848' city = 'Hörselberg' )
      ( client = sy-mandt postcode = '99867' city = 'Gotha' )
      ( client = sy-mandt postcode = '99869' city = 'Haina' )
      ( client = sy-mandt postcode = '99878' city = 'BSPayone GmbH' )
      ( client = sy-mandt postcode = '99880' city = 'Aspach' )
      ( client = sy-mandt postcode = '99885' city = 'Wölfis' )
      ( client = sy-mandt postcode = '99887' city = 'Petriroda' )
      ( client = sy-mandt postcode = '99891' city = 'Tabarz' )
      ( client = sy-mandt postcode = '99893' city = 'Citicorp Kartenservice GmbH' )
      ( client = sy-mandt postcode = '99894' city = 'Ernstroda' )
      ( client = sy-mandt postcode = '99897' city = 'Tambach-Dietharz' )
      ( client = sy-mandt postcode = '99947' city = 'Tottleben' )
      ( client = sy-mandt postcode = '99955' city = 'Urleben' )
      ( client = sy-mandt postcode = '99958' city = 'Tonna' )
      ( client = sy-mandt postcode = '99974' city = 'Mühlhausen' )
      ( client = sy-mandt postcode = '99976' city = 'Anrode' )
      ( client = sy-mandt postcode = '99986' city = 'Langula' )
      ( client = sy-mandt postcode = '99988' city = 'Heyerode' )
      ( client = sy-mandt postcode = '99991' city = 'Altengottern' )
      ( client = sy-mandt postcode = '99994' city = 'Schlotheim' )
      ( client = sy-mandt postcode = '99996' city = 'Menteroda' )
      ( client = sy-mandt postcode = '99998' city = 'Körner' )
    ).

    MODIFY zcs03_plz_city FROM TABLE @lt_plz.

    IF sy-subrc = 0.
      out->write( |{ lines( lt_plz ) } PLZ-Einträge eingefügt/aktualisiert (Teil 8 von 8)| ).
    ELSE.
      out->write( 'Fehler beim Einfügen' ).
    ENDIF.

    COMMIT WORK.

  ENDMETHOD.

ENDCLASS.
